export {default as setBar} from './setBar';
export {default as setColor} from './setColor';
export {default as setControl} from './setControl';
export {default as setConfig} from './setConfig';
export {default as setRange} from './setRange';
export {default as setRulers} from './setRulers';
export {default as setSlider} from './setSlider';
export {default as setTooltip} from './setTooltip';
export {default as setVertical} from './setVertical';
